api:
  API_Key: ""
  API_Secret_Key: ""
  Access_Token: ""
  Access_Token_Secret: ""

# オプション(除外する条件)
option:
  # 指定した数値以上RTされている場合除外(-1にすると条件を無効化)
  RT: -1
  # 指定した数値以上Favられている場合除外(-1にすると条件を無効化)
  Fav: -1
  # 指定した時間までのツイートは除外(空白は条件を無効化)
  Until: ""
  # 指定した時間より後のツイートは除外(空白は条件を無効化)
  Since: ""
  # 指定したハッシュタグを含む場合除外(空白は条件を無効化)
  Hashtag: ""